
# Note: lets you use {{ site.title}}
title: The Free World Fact Book


markdown: kramdown


# Note: let's store all our markdown sources, that is, book pages in the pages folder
include: ['_pages']

# Note: dotfiles are excluded by default (e.g. .gitignore)
exclude: ['README.md']


#################################################################
# used by GitHub pages, thus, also use these setting locally

safe: true
lsi: false
